/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FwbAvatar: typeof import('flowbite-vue')['FwbAvatar']
    FwbBackToTop: typeof import('flowbite-vue')['FwbBackToTop']
    FwbButton: typeof import('flowbite-vue')['FwbButton']
    FwbFooter: typeof import('flowbite-vue')['FwbFooter']
    FwbInput: typeof import('flowbite-vue')['FwbInput']
    FwbListGroup: typeof import('flowbite-vue')['FwbListGroup']
    FwbListGroupItem: typeof import('flowbite-vue')['FwbListGroupItem']
    FwbModal: typeof import('flowbite-vue')['FwbModal']
    FwbNavbarLogo: typeof import('flowbite-vue')['FwbNavbarLogo']
    FwbPagination: typeof import('flowbite-vue')['FwbPagination']
    FwbRadio: typeof import('flowbite-vue')['FwbRadio']
    FwbTab: typeof import('flowbite-vue')['FwbTab']
    FwbTable: typeof import('flowbite-vue')['FwbTable']
    FwbTableBody: typeof import('flowbite-vue')['FwbTableBody']
    FwbTableCell: typeof import('flowbite-vue')['FwbTableCell']
    FwbTableHead: typeof import('flowbite-vue')['FwbTableHead']
    FwbTableHeadCell: typeof import('flowbite-vue')['FwbTableHeadCell']
    FwbTableRow: typeof import('flowbite-vue')['FwbTableRow']
    FwbTabs: typeof import('flowbite-vue')['FwbTabs']
    FwbTextarea: typeof import('flowbite-vue')['FwbTextarea']
    FwbToast: typeof import('flowbite-vue')['FwbToast']
    FwbTooltip: typeof import('flowbite-vue')['FwbTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
